<?php
	if($topic=="articles"){
		include('admin_includes/article_manage/article_manage.php');
	}
	elseif($topic=="new_article"){
		include('admin_includes/article_manage/new_article.php');
	}
	elseif($topic=="articles_delete"){
		include('admin_includes/article_manage/article_delete.php');
	}
	elseif($topic=="articles_trash"){
		include('admin_includes/article_manage/articles_trash.php');
	}
	elseif($topic=="downloadmanager" || $topic=="publicationmanager" || $topic=="informationmanager" || $topic=="newsandeventmanager"){
		include('admin_includes/file_manager/filemanager.php');
	}
	elseif($topic=="adddownload" || $topic=="newpublication" || $topic=="newinformation" || $topic=="newnewsandevent"){
		include('admin_includes/file_manager/newfile.php');
	}
	elseif($topic=="downloaddelete" || $topic=="deletepublication" || $topic=="deleteinformation" || $topic=="deletenewsandevent"){
		include('admin_includes/file_manager/deletefile.php');
	}
	elseif($topic=="trashdownload" || $topic=="trashpublication" || $topic=="trashinformation" || $topic=="trashnewsandevent"){
		include('admin_includes/file_manager/trashfile.php');
	}
	elseif($topic=="virtuallearningmanager"){
		include('admin_includes/virtuallearningmanager/virtuallearningmanager.php');
	}
	elseif($topic=="addclass"){
		include('admin_includes/virtuallearningmanager/addclass.php');
	}
	elseif($topic=="editclass"){
		include('admin_includes/virtuallearningmanager/editclass.php');
	}
	elseif($topic=="addsubject"){
		include('admin_includes/virtuallearningmanager/addsubject.php');
	}
	elseif($topic=="editsubject"){
		include('admin_includes/virtuallearningmanager/editsubject.php');
	}
	elseif($topic=="addunit"){
		include('admin_includes/virtuallearningmanager/addunit.php');
	}
	elseif($topic=="editunit"){
		include('admin_includes/virtuallearningmanager/editunit.php');
	}
	elseif($topic=="addmeterials"){
		include('admin_includes/virtuallearningmanager/addmeterial.php');
	}
	elseif($topic=="editmeterial"){
		include('admin_includes/virtuallearningmanager/editmeterial.php');
	}
	elseif($topic=="productmanager"){
		include('admin_includes/productManager/productManager.php');
	}
	elseif($topic=="addproduct"){
		include('admin_includes/productManager/addProduct.php');
	}
	elseif($topic=="deleteproduct"){
		include('admin_includes/productManager/deleteProduct.php');
	}
	elseif($topic=="trashproduct"){
		include('admin_includes/productManager/trashProduct.php');
	}
	elseif($topic=="clientmanager"){
		include('admin_includes/clientmanager/clientmanager.php');
	}
	elseif($topic=="deleteclient"){
		include('admin_includes/clientmanager/delete.php');
	}
	elseif($topic=="category"){
		include('admin_includes/category_manage/category_manage.php');
	}
	elseif($topic=="category_add"){
		include('admin_includes/category_manage/add_category.php');
	}
	elseif($topic=="category_delete"){
		include('admin_includes/category_manage/delete_category.php');
	}
	elseif($topic=="categoty_trash"){
		include('admin_includes/category_manage/trash_category.php');
	}
	elseif($topic=="menu"){
		include('admin_includes/menu_manage/menu_manage.php');
	}
	elseif($topic=="menu_add"){
		include('admin_includes/menu_manage/add_menu.php');
	}
	elseif($topic=="menu_delete"){
		include('admin_includes/menu_manage/delete_menu.php');
	}
	elseif($topic=="menu_trash"){
		include('admin_includes/menu_manage/trash_menu.php');
	}
	
	
	elseif($topic=="faq"){
		include('admin_includes/faq_manager/faq_manage.php');
	}
	elseif($topic=="faq_add"){
		include('admin_includes/faq_manager/add_faq.php');
	}
	elseif($topic=="faq_delete"){
		include('admin_includes/faq_manager/delete_faq.php');
	}
	elseif($topic=="faq_trash"){
		include('admin_includes/faq_manager/trash_faq.php');
	}
	
	
	
	elseif($topic=="gallery"){
		include('admin_includes/gallery_manage/gallery_manage.php');
	}
	elseif($topic=="gallery_add"){
		include('admin_includes/gallery_manage/add_gallery.php');
	}
	elseif($topic=="galleryedit"){
		include('admin_includes/gallery_manage/edit_gallery.php');
	}
	elseif($topic=="gallery_edit"){
		include('admin_includes/gallery_manage/edit_gallery.php');
	}
	elseif($topic=="addgalleryitem"){
		include('admin_includes/gallery_manage/addgalleryitem.php');
	}
	elseif($topic=="editgalleryitem"){
		include('admin_includes/gallery_manage/editgalleryitem.php');
	}
	elseif($topic=="deletegalleryitem"){
		include('admin_includes/gallery_manage/deletegalleryitem.php');
	}
	elseif($topic=="trashgalleryitem"){
		include('admin_includes/gallery_manage/trashgalleryitem.php');
	}
	elseif($topic=="gallery_delete"){
		include('admin_includes/gallery_manage/delete_gallery.php');
	}
	elseif($topic=="gallery_image_delete"){
		include('admin_includes/gallery_manage/delete_image_gallery.php');
	}
	elseif($topic=="gallery_trash"){
		include('admin_includes/gallery_manage/trash_gallery.php');
	}
	elseif($topic=="gallery_image_trash"){
		include('admin_includes/gallery_manage/trash_image_gallery.php');
	}
	elseif($topic=="advertise"){
		include('admin_includes/add_manage/add_manage.php');
	}
	elseif($topic=="advertise_add"){
		include('admin_includes/add_manage/new_add.php');
	}
	elseif($topic=="advertise_delete"){
		include('admin_includes/add_manage/delete_add.php');
	}
	elseif($topic=="advertise_trash"){
		include('admin_includes/add_manage/add_trash.php');
	}
	elseif($topic=="setting"){
		include('admin_includes/setting/settingManager.php');
	}
	elseif($topic=="video"){
		include('admin_includes/video_manage/video_manage.php');
	}
	elseif($topic=="video_add"){
		include('admin_includes/video_manage/add_video.php');
	}
	elseif($topic=="video_edit"){
		include('admin_includes/video_manage/edit_video.php');
	}
	elseif($topic=="video_delete"){
		include('admin_includes/video_manage/delete_video.php');
	}
	elseif($topic=="video_trash"){
		include('admin_includes/video_manage/video_trash.php');
	}
	elseif($topic=="event_festible"){
		include('admin_includes/event_manager/set_event.php');
	}
	elseif($topic=="event_festible_remove"){
		include('admin_includes/event_manager/remove_event.php');
	}
	elseif($topic=="membertype"){
		include('admin_includes/memberManager/membercategory.php');
	}
	elseif($topic=="member"){
		include('admin_includes/memberManager/memberManager.php');
	}
	elseif($topic=="memberAdd"){
		include('admin_includes/memberManager/addMember.php');
	}
	elseif($topic=="memberDelete"){
		include('admin_includes/memberManager/deleteMember.php');
	}
	elseif($topic=="memberTrash"){
		include('admin_includes/memberManager/trashMember.php');
	}
	elseif($topic=="profile"){
		include('admin_includes/companyProfile/companyProfile.php');	
	}
	elseif($topic=="complain"){
		include('admin_includes/complain_manager/complain_manage.php');
	}
	elseif($topic=="help"){
		include('admin_includes/complain_manager/complain_manage.php');
	}
	
	
	
	
?>